### ISSUE TITLE
'NoneType' object has no attribute 'span'

### ISSUE THREAD

**Issue by cdrCraft** [JDLPIXEL/YT-Downloader#2]
Dieses Video Downloaden:
https://www.youtube.com/shorts/qP0fNQQYxAw
auch als Langes Video: https://www.youtube.com/watch?v=qP0fNQQYxAw

Error:
'NoneType' object has no attribute 'span'

Normaler MP4 download

**Comment by JDLPIXEL** [comment]
Guten Tag,
ich habe es gerade mit der Neusten Version vom September also der v2.3 ausprobiert. Die Shorts können erfolgreich heruntergeladen werden. 
Lösungsvorschlag: 
1. Programm neustarten
2. Programm als Administrator ausführen
3. Programm neu installieren https://jdlpixel.de/download.html

LG JDL_PIXEL
