### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by cdrCraft** [JDLPIXEL/YT-Downloader#3]
Beim download einer **Playlist** zu **mp3** ist ein Fehler aufgetreten: _HTTP Error 503: Service Unavailable_
Von den 114 Dateien wurden 4 erfolgreich heruntergeladen und eine Datei wurde als mp4 heruntergeladen. (ungewollt)

**Comment by JDLPIXEL** [comment]
Danke für die Fehlermeldung!
Ich benötige den Playlistlink um den Fehler nach zu voll ziehen zu können.

Grüße, JDL_PIXEL

**Comment by JDLPIXEL** [comment]
> Beim download einer **Playlist** zu **mp3** ist ein Fehler aufgetreten: _HTTP Error 503: Service Unavailable_ Von den 114 Dateien wurden 4 erfolgreich heruntergeladen und eine Datei wurde als mp4 heruntergeladen. (ungewollt)

Hallo nocheinmal,
der Fehler sollte nun mit dem neusten pre-release der [BETA-Version 2.3](https://github.com/JDLPIXEL/YT-Downloader/releases/download/v2.3-BETA/YouTube.Downloader-Setup-BETA-v2-3.exe) behoben sein.
Wichtig ist zu beachten, öffne die exe Date immer als Administrator oder Installiere Sie in keinem Verzeichnis wo Adminrechte benötigt werden um etwas an Dateien zu ändern.
